// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuzgqDwxUrxopLgVYSyCzdvdMEZ8WOFdE',
    appId: '1:510938043145:web:975a7f9d1d0b687f1d79d8',
    messagingSenderId: '510938043145',
    projectId: 'emart-2557a',
    authDomain: 'emart-2557a.firebaseapp.com',
    storageBucket: 'emart-2557a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrSXjtQHf0pz7nDR1zcd5q4O4V5tEqwiw',
    appId: '1:510938043145:android:880d0d341c8b87c71d79d8',
    messagingSenderId: '510938043145',
    projectId: 'emart-2557a',
    storageBucket: 'emart-2557a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASQSmuTBeda9WGliQ3ULEpvCHrh5NlrU4',
    appId: '1:510938043145:ios:0bd6ec9fa635a5ab1d79d8',
    messagingSenderId: '510938043145',
    projectId: 'emart-2557a',
    storageBucket: 'emart-2557a.firebasestorage.app',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASQSmuTBeda9WGliQ3ULEpvCHrh5NlrU4',
    appId: '1:510938043145:ios:0bd6ec9fa635a5ab1d79d8',
    messagingSenderId: '510938043145',
    projectId: 'emart-2557a',
    storageBucket: 'emart-2557a.firebasestorage.app',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuzgqDwxUrxopLgVYSyCzdvdMEZ8WOFdE',
    appId: '1:510938043145:web:75a7ebc43c7298b51d79d8',
    messagingSenderId: '510938043145',
    projectId: 'emart-2557a',
    authDomain: 'emart-2557a.firebaseapp.com',
    storageBucket: 'emart-2557a.firebasestorage.app',
  );
}
